#
# Vivado (TM) v2014.3 (64-bit)
#
# recreate-vivado-project.tcl: Tcl script for re-creating project 'multes_proj'
#
# Generated by Vivado on Fri Oct 12 16:46:29 CEST 2018
# IP Build 1028902 on Fri Sep 26 17:35:13 MDT 2014
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (recreate-vivado-project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "/srv/local/zistvan/workspace/multes/hw/src/muu/muu_tokenbucket.v"
#    "/srv/local/zistvan/workspace/multes/hw/src/zookeep/data/kvs_LatchedRelay.vhdl"
#    "/srv/local/zistvan/workspace/multes/hw/src/nukv/nukv_fifogen.v"
#    "/srv/local/zistvan/workspace/multes/hw/src/muu/muu_value_set.v"
#    "/srv/local/zistvan/workspace/multes/hw/src/muu/muu_value_get.v"
#    "/srv/local/zistvan/workspace/multes/hw/src/muu/muu_requestsplit.v"
#    "/srv/local/zistvan/workspace/multes/hw/src/muu/muu_replicate_LogManager.vhdl"
#    "/srv/local/zistvan/workspace/multes/hw/src/muu/muu_replicate_CentralSM.vhdl"
#    "/srv/local/zistvan/workspace/multes/hw/src/muu/muu_ht_write.v"
#    "/srv/local/zistvan/workspace/multes/hw/src/muu/muu_ht_read.v"
#    "/srv/local/zistvan/workspace/multes/hw/src/muu/muu_datarepeater.v"
#    "/srv/local/zistvan/workspace/multes/hw/src/muu/muu_checkpoint.v"
#    "/srv/local/zistvan/workspace/multes/hw/src/net/tx_interface.v"
#    "/srv/local/zistvan/workspace/multes/hw/src/net/ten_gig_eth_pcs_pma_ip_GT_Common_wrapper.v"
#    "/srv/local/zistvan/workspace/multes/hw/src/net/rx_interface.v"
#    "/srv/local/zistvan/workspace/multes/hw/src/net/clock_control/kcpsm6.vhd"
#    "/srv/local/zistvan/workspace/multes/hw/src/net/clock_control/clock_control_program.vhd"
#    "/srv/local/zistvan/workspace/multes/hw/src/zookeep/session/zk_session_Filter.vhdl"
#    "/srv/local/zistvan/workspace/multes/hw/src/nukv/nukv_malloc_v2.v"
#    "/srv/local/zistvan/workspace/multes/hw/ip/chipscope/vio.ngc"
#    "/srv/local/zistvan/workspace/multes/hw/ip/chipscope/ila_256.ngc"
#    "/srv/local/zistvan/workspace/multes/hw/ip/chipscope/icon.ngc"
#    "/srv/local/zistvan/workspace/multes/hw/ip/chipscope/vio.v"
#    "/srv/local/zistvan/workspace/multes/hw/ip/chipscope/icon.v"
#    "/srv/local/zistvan/workspace/multes/hw/ip/chipscope/ila_256.v"
#    "/srv/local/zistvan/workspace/multes/hw/ip/system-dcp/mig_axi_mm_dual.dcp"
#    "/srv/local/zistvan/workspace/multes/hw/src/net/ddr3_dual_inf.v"
#    "/srv/local/zistvan/workspace/multes/hw/src/muu/muu_top_module_wrepl.v"
#    "/srv/local/zistvan/workspace/multes/hw/src/muu/muu_session_Top.vhd"
#    "/srv/local/zistvan/workspace/multes/hw/src/net/xgbaser_gt_same_quad_wrapper.v"
#    "/srv/local/zistvan/workspace/multes/hw/src/net/network_module.v"
#    "/srv/local/zistvan/workspace/multes/hw/src/net/clock_control/clock_control.vhd"
#    "/srv/local/zistvan/workspace/multes/hw/ip/system-dcp/SmartCamCtl.dcp"
#    "/srv/local/zistvan/workspace/multes/hw/ip/system/arp_server_subnet_ip/arp_server_subnet_ip.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/system/icmp_server_ip/icmp_server_ip.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/system/mac_ip_encode_ip/mac_ip_encode_ip.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/system/shortcut_toe_NODELAY_ip/shortcut_toe_NODELAY_ip.xci"
#    "/srv/local/zistvan/workspace/multes/hw/src/muu/muu_topwrapper.v"
#    "/srv/local/zistvan/workspace/multes/hw/src/net/vc709_10g_interface.v"
#    "/srv/local/zistvan/workspace/multes/hw/src/net/tcp_ip_wrapper.v"
#    "/srv/local/zistvan/workspace/multes/hw/src/nukv/nkv_ddr_mem_inf_tcp.v"
#    "/srv/local/zistvan/workspace/multes/hw/src/zookeep/top/zookeeper_nkv_fpga_para.v"
#    "/srv/local/zistvan/workspace/multes/hw/ip/system/mig_axi_mm_dual/mig_a.prj"
#    "/srv/local/zistvan/workspace/multes/hw/src/mock_dram/kvs_tbDRAMHDLNode.vhdl"
#    "/srv/local/zistvan/workspace/multes/hw/src/mock_dram/bram_gen.vhdl"
#    "/srv/local/zistvan/workspace/multes/hw/src/muu/zk_toplevel_muu_TB.vhdl"
#    "/srv/local/zistvan/workspace/multes/hw/src/nukv/kvs_tbDRAM_Module.vhdl"
#    "/srv/local/zistvan/workspace/multes/hw/ip/dramsim/fifogen_dram_cmd_in/fifogen_dram_cmd_in.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/dramsim/fifogen_dram_data_out/fifogen_dram_data_out.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/dramsim/fifogen_dram_data_in/fifogen_dram_data_in.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/system/mig_axi_mm_dual/mig_b.prj"
#    "/srv/local/zistvan/workspace/multes/hw/ip/system/cmd_fifo_xgemac_txif/cmd_fifo_xgemac_txif.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/system/cmd_fifo_xgemac_rxif/cmd_fifo_xgemac_rxif.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/system/axis_sync_fifo/axis_sync_fifo.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/zookeeper/zk_blkmem_32x1024/zk_blkmem_32x1024.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/system/ten_gig_eth_pcs_pma_ip/ten_gig_eth_pcs_pma_ip.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/system/ten_gig_eth_mac_ip/ten_gig_eth_mac_ip.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/system/axis_register_slice_64/axis_register_slice_64.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/muu/fifo_256bit_regslice/fifo_256bit_regslice.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/muu/fifo_512bit_regslice/fifo_512bit_regslice.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/muu/fifo_64bit_regslice/fifo_64bit_regslice.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/zookeeper/zk_fifo_128x1024/zk_fifo_128x1024.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/system/fifo_dm_to_kvs_s/fifo_dm_to_kvs_s.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/system/axi_write_tcp_datamover/axi_write_tcp_datamover.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/system/axi_write_kvs_datamover/axi_write_kvs_datamover.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/system/axi_read_tcp_datamover/axi_read_tcp_datamover.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/system/axi_read_kvs_datamover/axi_read_kvs_datamover.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/system/axi_kvs_mem_interconnect_3/axi_kvs_mem_interconnect_3.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/system/axis_data_fifo_tcp_to_dm_64/axis_data_fifo_tcp_to_dm_64.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/system/axis_data_fifo_kvs_to_dm_512/axis_data_fifo_kvs_to_dm_512.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/system/fifo_generator_0/fifo_generator_0.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/system/axis_interconnect_3to1/axis_interconnect_3to1.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/system/axis_interconnect_2to1/axis_interconnect_2to1.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/zookeeper/axis_data_fifo_cmd64/axis_data_fifo_cmd64.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/zookeeper/axi_kvs_mem_interconnect/axi_kvs_mem_interconnect.xci"
#    "/srv/local/zistvan/workspace/multes/hw/ip/system/ip_handler_ip/ip_handler_ip.xci"
#    "/srv/local/zistvan/workspace/multes/hw/constraints/multiple-nics.xdc"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/multes_proj"]"

# Create project
create_project multes_proj ./multes_proj

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [get_projects multes_proj]
set_property "board_part" "xilinx.com:vc709:part0:1.4" $obj
set_property "default_lib" "xil_defaultlib" $obj
set_property "simulator_language" "Mixed" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
set obj [get_filesets sources_1]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../iprepository"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hw/src/muu/muu_tokenbucket.v"]"\
 "[file normalize "$origin_dir/hw/src/zookeep/data/kvs_LatchedRelay.vhdl"]"\
 "[file normalize "$origin_dir/hw/src/nukv/nukv_fifogen.v"]"\
 "[file normalize "$origin_dir/hw/src/muu/muu_value_set.v"]"\
 "[file normalize "$origin_dir/hw/src/muu/muu_value_get.v"]"\
 "[file normalize "$origin_dir/hw/src/muu/muu_requestsplit.v"]"\
 "[file normalize "$origin_dir/hw/src/muu/muu_replicate_LogManager.vhdl"]"\
 "[file normalize "$origin_dir/hw/src/muu/muu_replicate_CentralSM.vhdl"]"\
 "[file normalize "$origin_dir/hw/src/muu/muu_ht_write.v"]"\
 "[file normalize "$origin_dir/hw/src/muu/muu_ht_read.v"]"\
 "[file normalize "$origin_dir/hw/src/muu/muu_datarepeater.v"]"\
 "[file normalize "$origin_dir/hw/src/muu/muu_checkpoint.v"]"\
 "[file normalize "$origin_dir/hw/src/net/tx_interface.v"]"\
 "[file normalize "$origin_dir/hw/src/net/ten_gig_eth_pcs_pma_ip_GT_Common_wrapper.v"]"\
 "[file normalize "$origin_dir/hw/src/net/rx_interface.v"]"\
 "[file normalize "$origin_dir/hw/src/net/clock_control/kcpsm6.vhd"]"\
 "[file normalize "$origin_dir/hw/src/net/clock_control/clock_control_program.vhd"]"\
 "[file normalize "$origin_dir/hw/src/zookeep/session/zk_session_Filter.vhdl"]"\
 "[file normalize "$origin_dir/hw/src/nukv/nukv_malloc_v2.v"]"\
 "[file normalize "$origin_dir/hw/ip/chipscope/vio.ngc"]"\
 "[file normalize "$origin_dir/hw/ip/chipscope/ila_256.ngc"]"\
 "[file normalize "$origin_dir/hw/ip/chipscope/icon.ngc"]"\
 "[file normalize "$origin_dir/hw/ip/chipscope/vio.v"]"\
 "[file normalize "$origin_dir/hw/ip/chipscope/icon.v"]"\
 "[file normalize "$origin_dir/hw/ip/chipscope/ila_256.v"]"\
 "[file normalize "$origin_dir/hw/ip/system-dcp/mig_axi_mm_dual.dcp"]"\
 "[file normalize "$origin_dir/hw/src/net/ddr3_dual_inf.v"]"\
 "[file normalize "$origin_dir/hw/src/muu/muu_top_module_wrepl.v"]"\
 "[file normalize "$origin_dir/hw/src/muu/muu_session_Top.vhd"]"\
 "[file normalize "$origin_dir/hw/src/net/xgbaser_gt_same_quad_wrapper.v"]"\
 "[file normalize "$origin_dir/hw/src/net/network_module.v"]"\
 "[file normalize "$origin_dir/hw/src/net/clock_control/clock_control.vhd"]"\
 "[file normalize "$origin_dir/hw/ip/system-dcp/SmartCamCtl.dcp"]"\
 "[file normalize "$origin_dir/hw/ip/system/arp_server_subnet_ip/arp_server_subnet_ip.xci"]"\
 "[file normalize "$origin_dir/hw/ip/system/icmp_server_ip/icmp_server_ip.xci"]"\
 "[file normalize "$origin_dir/hw/ip/system/mac_ip_encode_ip/mac_ip_encode_ip.xci"]"\
 "[file normalize "$origin_dir/hw/ip/system/shortcut_toe_NODELAY_ip/shortcut_toe_NODELAY_ip.xci"]"\
 "[file normalize "$origin_dir/hw/src/muu/muu_topwrapper.v"]"\
 "[file normalize "$origin_dir/hw/src/net/vc709_10g_interface.v"]"\
 "[file normalize "$origin_dir/hw/src/net/tcp_ip_wrapper.v"]"\
 "[file normalize "$origin_dir/hw/src/nukv/nkv_ddr_mem_inf_tcp.v"]"\
 "[file normalize "$origin_dir/hw/src/zookeep/top/zookeeper_nkv_fpga_para.v"]"\
 "[file normalize "$origin_dir/hw/ip/system/mig_axi_mm_dual/mig_a.prj"]"\
 "[file normalize "$origin_dir/hw/src/mock_dram/kvs_tbDRAMHDLNode.vhdl"]"\
 "[file normalize "$origin_dir/hw/src/mock_dram/bram_gen.vhdl"]"\
 "[file normalize "$origin_dir/hw/src/muu/zk_toplevel_muu_TB.vhdl"]"\
 "[file normalize "$origin_dir/hw/src/nukv/kvs_tbDRAM_Module.vhdl"]"\
 "[file normalize "$origin_dir/hw/ip/dramsim/fifogen_dram_cmd_in/fifogen_dram_cmd_in.xci"]"\
 "[file normalize "$origin_dir/hw/ip/dramsim/fifogen_dram_data_out/fifogen_dram_data_out.xci"]"\
 "[file normalize "$origin_dir/hw/ip/dramsim/fifogen_dram_data_in/fifogen_dram_data_in.xci"]"\
 "[file normalize "$origin_dir/hw/ip/system/mig_axi_mm_dual/mig_b.prj"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hw/src/zookeep/data/kvs_LatchedRelay.vhdl"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/hw/src/muu/muu_replicate_LogManager.vhdl"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/hw/src/muu/muu_replicate_CentralSM.vhdl"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/hw/src/net/clock_control/kcpsm6.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/hw/src/net/clock_control/clock_control_program.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/hw/src/zookeep/session/zk_session_Filter.vhdl"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/hw/ip/chipscope/vio.ngc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "NGC" $file_obj

set file "$origin_dir/hw/ip/chipscope/ila_256.ngc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "NGC" $file_obj

set file "$origin_dir/hw/ip/chipscope/icon.ngc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "NGC" $file_obj

set file "$origin_dir/hw/src/muu/muu_session_Top.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/hw/src/net/clock_control/clock_control.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/hw/ip/system/mac_ip_encode_ip/mac_ip_encode_ip.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj

set file "$origin_dir/hw/ip/system/shortcut_toe_NODELAY_ip/shortcut_toe_NODELAY_ip.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj

set file "$origin_dir/hw/src/mock_dram/kvs_tbDRAMHDLNode.vhdl"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/hw/src/mock_dram/bram_gen.vhdl"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/hw/src/muu/zk_toplevel_muu_TB.vhdl"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/hw/src/nukv/kvs_tbDRAM_Module.vhdl"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "$origin_dir/hw/ip/dramsim/fifogen_dram_cmd_in/fifogen_dram_cmd_in.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj

set file "$origin_dir/hw/ip/dramsim/fifogen_dram_data_out/fifogen_dram_data_out.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj

set file "$origin_dir/hw/ip/dramsim/fifogen_dram_data_in/fifogen_dram_data_in.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "topmost_zooknukv_para" $obj

# Set IP repository paths
set obj [get_filesets cmd_fifo_xgemac_txif]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../iprepository"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hw/ip/system/cmd_fifo_xgemac_txif/cmd_fifo_xgemac_txif.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hw/ip/system/cmd_fifo_xgemac_txif/cmd_fifo_xgemac_txif.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set IP repository paths
set obj [get_filesets cmd_fifo_xgemac_rxif]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../iprepository"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hw/ip/system/cmd_fifo_xgemac_rxif/cmd_fifo_xgemac_rxif.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hw/ip/system/cmd_fifo_xgemac_rxif/cmd_fifo_xgemac_rxif.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set IP repository paths
set obj [get_filesets axis_sync_fifo]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../iprepository"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hw/ip/system/axis_sync_fifo/axis_sync_fifo.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hw/ip/system/axis_sync_fifo/axis_sync_fifo.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set IP repository paths
set obj [get_filesets zk_blkmem_32x1024]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../iprepository"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hw/ip/zookeeper/zk_blkmem_32x1024/zk_blkmem_32x1024.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hw/ip/zookeeper/zk_blkmem_32x1024/zk_blkmem_32x1024.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set IP repository paths
set obj [get_filesets ten_gig_eth_pcs_pma_ip]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../iprepository"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hw/ip/system/ten_gig_eth_pcs_pma_ip/ten_gig_eth_pcs_pma_ip.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hw/ip/system/ten_gig_eth_pcs_pma_ip/ten_gig_eth_pcs_pma_ip.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set IP repository paths
set obj [get_filesets ten_gig_eth_mac_ip]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../iprepository"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hw/ip/system/ten_gig_eth_mac_ip/ten_gig_eth_mac_ip.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hw/ip/system/ten_gig_eth_mac_ip/ten_gig_eth_mac_ip.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set IP repository paths
set obj [get_filesets axis_register_slice_64]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../iprepository"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hw/ip/system/axis_register_slice_64/axis_register_slice_64.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hw/ip/system/axis_register_slice_64/axis_register_slice_64.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set IP repository paths
set obj [get_filesets fifo_256bit_regslice]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../iprepository"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hw/ip/muu/fifo_256bit_regslice/fifo_256bit_regslice.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hw/ip/muu/fifo_256bit_regslice/fifo_256bit_regslice.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set IP repository paths
set obj [get_filesets fifo_512bit_regslice]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../iprepository"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hw/ip/muu/fifo_512bit_regslice/fifo_512bit_regslice.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hw/ip/muu/fifo_512bit_regslice/fifo_512bit_regslice.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set IP repository paths
set obj [get_filesets fifo_64bit_regslice]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../iprepository"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hw/ip/muu/fifo_64bit_regslice/fifo_64bit_regslice.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hw/ip/muu/fifo_64bit_regslice/fifo_64bit_regslice.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set IP repository paths
set obj [get_filesets zk_fifo_128x1024]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../iprepository"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hw/ip/zookeeper/zk_fifo_128x1024/zk_fifo_128x1024.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hw/ip/zookeeper/zk_fifo_128x1024/zk_fifo_128x1024.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set IP repository paths
set obj [get_filesets fifo_dm_to_kvs_s]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../iprepository"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hw/ip/system/fifo_dm_to_kvs_s/fifo_dm_to_kvs_s.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hw/ip/system/fifo_dm_to_kvs_s/fifo_dm_to_kvs_s.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set IP repository paths
set obj [get_filesets axi_write_tcp_datamover]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../iprepository"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hw/ip/system/axi_write_tcp_datamover/axi_write_tcp_datamover.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hw/ip/system/axi_write_tcp_datamover/axi_write_tcp_datamover.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set IP repository paths
set obj [get_filesets axi_write_kvs_datamover]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../iprepository"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hw/ip/system/axi_write_kvs_datamover/axi_write_kvs_datamover.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hw/ip/system/axi_write_kvs_datamover/axi_write_kvs_datamover.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set IP repository paths
set obj [get_filesets axi_read_tcp_datamover]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../iprepository"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hw/ip/system/axi_read_tcp_datamover/axi_read_tcp_datamover.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hw/ip/system/axi_read_tcp_datamover/axi_read_tcp_datamover.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set IP repository paths
set obj [get_filesets axi_read_kvs_datamover]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../iprepository"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hw/ip/system/axi_read_kvs_datamover/axi_read_kvs_datamover.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hw/ip/system/axi_read_kvs_datamover/axi_read_kvs_datamover.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set IP repository paths
set obj [get_filesets axi_kvs_mem_interconnect_3]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../iprepository"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hw/ip/system/axi_kvs_mem_interconnect_3/axi_kvs_mem_interconnect_3.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hw/ip/system/axi_kvs_mem_interconnect_3/axi_kvs_mem_interconnect_3.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set IP repository paths
set obj [get_filesets axis_data_fifo_tcp_to_dm_64]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../iprepository"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hw/ip/system/axis_data_fifo_tcp_to_dm_64/axis_data_fifo_tcp_to_dm_64.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hw/ip/system/axis_data_fifo_tcp_to_dm_64/axis_data_fifo_tcp_to_dm_64.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set IP repository paths
set obj [get_filesets axis_data_fifo_kvs_to_dm_512]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../iprepository"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hw/ip/system/axis_data_fifo_kvs_to_dm_512/axis_data_fifo_kvs_to_dm_512.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hw/ip/system/axis_data_fifo_kvs_to_dm_512/axis_data_fifo_kvs_to_dm_512.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set IP repository paths
set obj [get_filesets fifo_generator_0]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../iprepository"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hw/ip/system/fifo_generator_0/fifo_generator_0.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hw/ip/system/fifo_generator_0/fifo_generator_0.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set IP repository paths
set obj [get_filesets axis_interconnect_3to1]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../iprepository"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hw/ip/system/axis_interconnect_3to1/axis_interconnect_3to1.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hw/ip/system/axis_interconnect_3to1/axis_interconnect_3to1.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set IP repository paths
set obj [get_filesets axis_interconnect_2to1]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../iprepository"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hw/ip/system/axis_interconnect_2to1/axis_interconnect_2to1.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hw/ip/system/axis_interconnect_2to1/axis_interconnect_2to1.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set IP repository paths
set obj [get_filesets axis_data_fifo_cmd64]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../iprepository"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hw/ip/zookeeper/axis_data_fifo_cmd64/axis_data_fifo_cmd64.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hw/ip/zookeeper/axis_data_fifo_cmd64/axis_data_fifo_cmd64.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set IP repository paths
set obj [get_filesets axi_kvs_mem_interconnect]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../iprepository"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hw/ip/zookeeper/axi_kvs_mem_interconnect/axi_kvs_mem_interconnect.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hw/ip/zookeeper/axi_kvs_mem_interconnect/axi_kvs_mem_interconnect.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set IP repository paths
set obj [get_filesets ip_handler_ip]
set_property "ip_repo_paths" "[file normalize "$origin_dir/../iprepository"]" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/hw/ip/system/ip_handler_ip/ip_handler_ip.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/hw/ip/system/ip_handler_ip/ip_handler_ip.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "synth_checkpoint_mode" "Singular" $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/hw/constraints/multiple-nics.xdc"]"
set file_added [add_files -norecurse -fileset $obj $file]
set file "$origin_dir/hw/constraints/multiple-nics.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property "file_type" "XDC" $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property "target_constrs_file" "[file normalize "$origin_dir/hw/constraints/multiple-nics.xdc"]" $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "zk_toplevel_muu_TB" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7vx690tffg1761-2 -flow {Vivado Synthesis 2014} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2014" [get_runs synth_1]
}
set obj [get_runs synth_1]

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7vx690tffg1761-2 -flow {Vivado Implementation 2014} -strategy "Performance_Explore" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Performance_Explore" [get_runs impl_1]
  set_property flow "Vivado Implementation 2014" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "steps.opt_design.args.directive" "Explore" $obj
set_property "steps.place_design.args.directive" "Explore" $obj
set_property "steps.phys_opt_design.is_enabled" "1" $obj
set_property "steps.phys_opt_design.args.directive" "Explore" $obj
set_property "steps.route_design.args.directive" "Explore" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:multes_proj"
