set_property PACKAGE_PIN BB39 [get_ports c0_ddr4_act_n]
set_property PACKAGE_PIN AT36 [get_ports {c0_ddr4_adr[0]}]
set_property PACKAGE_PIN AV36 [get_ports {c0_ddr4_adr[1]}]
set_property PACKAGE_PIN AV37 [get_ports {c0_ddr4_adr[2]}]
set_property PACKAGE_PIN AW35 [get_ports {c0_ddr4_adr[3]}]
set_property PACKAGE_PIN AW36 [get_ports {c0_ddr4_adr[4]}]
set_property PACKAGE_PIN AY36 [get_ports {c0_ddr4_adr[5]}]
set_property PACKAGE_PIN AY35 [get_ports {c0_ddr4_adr[6]}]
set_property PACKAGE_PIN BA40 [get_ports {c0_ddr4_adr[7]}]
set_property PACKAGE_PIN BA37 [get_ports {c0_ddr4_adr[8]}]
set_property PACKAGE_PIN BB37 [get_ports {c0_ddr4_adr[9]}]
set_property PACKAGE_PIN AR35 [get_ports {c0_ddr4_adr[10]}]
set_property PACKAGE_PIN BA39 [get_ports {c0_ddr4_adr[11]}]
set_property PACKAGE_PIN BB40 [get_ports {c0_ddr4_adr[12]}]
set_property PACKAGE_PIN AN36 [get_ports {c0_ddr4_adr[13]}]
set_property PACKAGE_PIN AP35 [get_ports {c0_ddr4_adr[14]}]
set_property PACKAGE_PIN AP36 [get_ports {c0_ddr4_adr[15]}]
set_property PACKAGE_PIN AR36 [get_ports {c0_ddr4_adr[16]}]
set_property PACKAGE_PIN AT35 [get_ports {c0_ddr4_ba[0]}]
set_property PACKAGE_PIN AT34 [get_ports {c0_ddr4_ba[1]}]
set_property PACKAGE_PIN BC37 [get_ports {c0_ddr4_bg[0]}]
set_property PACKAGE_PIN BC39 [get_ports {c0_ddr4_bg[1]}]
set_property PACKAGE_PIN BC38 [get_ports {c0_ddr4_cke[0]}]
set_property PACKAGE_PIN AR33 [get_ports {c0_ddr4_cs_n[0]}]
set_property PACKAGE_PIN AW28 [get_ports {c0_ddr4_dq[0]}]
set_property PACKAGE_PIN AW29 [get_ports {c0_ddr4_dq[1]}]
set_property PACKAGE_PIN BA28 [get_ports {c0_ddr4_dq[2]}]
set_property PACKAGE_PIN BA27 [get_ports {c0_ddr4_dq[3]}]
set_property PACKAGE_PIN BB29 [get_ports {c0_ddr4_dq[4]}]
set_property PACKAGE_PIN BA29 [get_ports {c0_ddr4_dq[5]}]
set_property PACKAGE_PIN BC27 [get_ports {c0_ddr4_dq[6]}]
set_property PACKAGE_PIN BB27 [get_ports {c0_ddr4_dq[7]}]
set_property PACKAGE_PIN BE28 [get_ports {c0_ddr4_dq[8]}]
set_property PACKAGE_PIN BF28 [get_ports {c0_ddr4_dq[9]}]
set_property PACKAGE_PIN BE30 [get_ports {c0_ddr4_dq[10]}]
set_property PACKAGE_PIN BD30 [get_ports {c0_ddr4_dq[11]}]
set_property PACKAGE_PIN BF27 [get_ports {c0_ddr4_dq[12]}]
set_property PACKAGE_PIN BE27 [get_ports {c0_ddr4_dq[13]}]
set_property PACKAGE_PIN BF30 [get_ports {c0_ddr4_dq[14]}]
set_property PACKAGE_PIN BF29 [get_ports {c0_ddr4_dq[15]}]
set_property PACKAGE_PIN BB31 [get_ports {c0_ddr4_dq[16]}]
set_property PACKAGE_PIN BB32 [get_ports {c0_ddr4_dq[17]}]
set_property PACKAGE_PIN AY32 [get_ports {c0_ddr4_dq[18]}]
set_property PACKAGE_PIN AY33 [get_ports {c0_ddr4_dq[19]}]
set_property PACKAGE_PIN BC32 [get_ports {c0_ddr4_dq[20]}]
set_property PACKAGE_PIN BC33 [get_ports {c0_ddr4_dq[21]}]
set_property PACKAGE_PIN BB34 [get_ports {c0_ddr4_dq[22]}]
set_property PACKAGE_PIN BC34 [get_ports {c0_ddr4_dq[23]}]
set_property PACKAGE_PIN AV31 [get_ports {c0_ddr4_dq[24]}]
set_property PACKAGE_PIN AV32 [get_ports {c0_ddr4_dq[25]}]
set_property PACKAGE_PIN AV34 [get_ports {c0_ddr4_dq[26]}]
set_property PACKAGE_PIN AW34 [get_ports {c0_ddr4_dq[27]}]
set_property PACKAGE_PIN AW31 [get_ports {c0_ddr4_dq[28]}]
set_property PACKAGE_PIN AY31 [get_ports {c0_ddr4_dq[29]}]
set_property PACKAGE_PIN BA35 [get_ports {c0_ddr4_dq[30]}]
set_property PACKAGE_PIN BA34 [get_ports {c0_ddr4_dq[31]}]
set_property PACKAGE_PIN AL30 [get_ports {c0_ddr4_dq[32]}]
set_property PACKAGE_PIN AM30 [get_ports {c0_ddr4_dq[33]}]
set_property PACKAGE_PIN AU32 [get_ports {c0_ddr4_dq[34]}]
set_property PACKAGE_PIN AT32 [get_ports {c0_ddr4_dq[35]}]
set_property PACKAGE_PIN AN31 [get_ports {c0_ddr4_dq[36]}]
set_property PACKAGE_PIN AN32 [get_ports {c0_ddr4_dq[37]}]
set_property PACKAGE_PIN AR32 [get_ports {c0_ddr4_dq[38]}]
set_property PACKAGE_PIN AR31 [get_ports {c0_ddr4_dq[39]}]
set_property PACKAGE_PIN AP29 [get_ports {c0_ddr4_dq[40]}]
set_property PACKAGE_PIN AP28 [get_ports {c0_ddr4_dq[41]}]
set_property PACKAGE_PIN AN27 [get_ports {c0_ddr4_dq[42]}]
set_property PACKAGE_PIN AM27 [get_ports {c0_ddr4_dq[43]}]
set_property PACKAGE_PIN AN29 [get_ports {c0_ddr4_dq[44]}]
set_property PACKAGE_PIN AM29 [get_ports {c0_ddr4_dq[45]}]
set_property PACKAGE_PIN AR27 [get_ports {c0_ddr4_dq[46]}]
set_property PACKAGE_PIN AR28 [get_ports {c0_ddr4_dq[47]}]
set_property PACKAGE_PIN AT28 [get_ports {c0_ddr4_dq[48]}]
set_property PACKAGE_PIN AV27 [get_ports {c0_ddr4_dq[49]}]
set_property PACKAGE_PIN AU27 [get_ports {c0_ddr4_dq[50]}]
set_property PACKAGE_PIN AT27 [get_ports {c0_ddr4_dq[51]}]
set_property PACKAGE_PIN AV29 [get_ports {c0_ddr4_dq[52]}]
set_property PACKAGE_PIN AY30 [get_ports {c0_ddr4_dq[53]}]
set_property PACKAGE_PIN AW30 [get_ports {c0_ddr4_dq[54]}]
set_property PACKAGE_PIN AV28 [get_ports {c0_ddr4_dq[55]}]
set_property PACKAGE_PIN BD34 [get_ports {c0_ddr4_dq[56]}]
set_property PACKAGE_PIN BD33 [get_ports {c0_ddr4_dq[57]}]
set_property PACKAGE_PIN BE33 [get_ports {c0_ddr4_dq[58]}]
set_property PACKAGE_PIN BD35 [get_ports {c0_ddr4_dq[59]}]
set_property PACKAGE_PIN BF32 [get_ports {c0_ddr4_dq[60]}]
set_property PACKAGE_PIN BF33 [get_ports {c0_ddr4_dq[61]}]
set_property PACKAGE_PIN BF34 [get_ports {c0_ddr4_dq[62]}]
set_property PACKAGE_PIN BF35 [get_ports {c0_ddr4_dq[63]}]
set_property PACKAGE_PIN BD40 [get_ports {c0_ddr4_dq[64]}]
set_property PACKAGE_PIN BD39 [get_ports {c0_ddr4_dq[65]}]
set_property PACKAGE_PIN BF43 [get_ports {c0_ddr4_dq[66]}]
set_property PACKAGE_PIN BF42 [get_ports {c0_ddr4_dq[67]}]
set_property PACKAGE_PIN BF37 [get_ports {c0_ddr4_dq[68]}]
set_property PACKAGE_PIN BE37 [get_ports {c0_ddr4_dq[69]}]
set_property PACKAGE_PIN BE40 [get_ports {c0_ddr4_dq[70]}]
set_property PACKAGE_PIN BF41 [get_ports {c0_ddr4_dq[71]}]
set_property PACKAGE_PIN AP34 [get_ports {c0_ddr4_odt[0]}]
set_property PACKAGE_PIN AU31 [get_ports c0_ddr4_reset_n]
set_property PACKAGE_PIN AU36 [get_ports c0_ddr4_parity]
set_property PACKAGE_PIN AY37 [get_ports c0_sys_clk_p]
set_property PACKAGE_PIN AY38 [get_ports c0_sys_clk_n]
set_property PACKAGE_PIN BA30 [get_ports {c0_ddr4_dqs_t[0]}]
set_property PACKAGE_PIN BB30 [get_ports {c0_ddr4_dqs_c[0]}]
set_property PACKAGE_PIN AM31 [get_ports {c0_ddr4_dqs_t[8]}]
set_property PACKAGE_PIN AM32 [get_ports {c0_ddr4_dqs_c[8]}]
set_property PACKAGE_PIN BE38 [get_ports {c0_ddr4_dqs_t[16]}]
set_property PACKAGE_PIN BF38 [get_ports {c0_ddr4_dqs_c[16]}]
set_property PACKAGE_PIN AP30 [get_ports {c0_ddr4_dqs_t[9]}]
set_property PACKAGE_PIN AP31 [get_ports {c0_ddr4_dqs_c[9]}]
set_property PACKAGE_PIN BB26 [get_ports {c0_ddr4_dqs_t[1]}]
set_property PACKAGE_PIN BC26 [get_ports {c0_ddr4_dqs_c[1]}]
set_property PACKAGE_PIN BF39 [get_ports {c0_ddr4_dqs_t[17]}]
set_property PACKAGE_PIN BF40 [get_ports {c0_ddr4_dqs_c[17]}]
set_property PACKAGE_PIN BE35 [get_ports {c0_ddr4_dqs_t[14]}]
set_property PACKAGE_PIN BE36 [get_ports {c0_ddr4_dqs_c[14]}]
set_property PACKAGE_PIN AV33 [get_ports {c0_ddr4_dqs_t[6]}]
set_property PACKAGE_PIN AW33 [get_ports {c0_ddr4_dqs_c[6]}]
set_property PACKAGE_PIN BE31 [get_ports {c0_ddr4_dqs_t[15]}]
set_property PACKAGE_PIN BE32 [get_ports {c0_ddr4_dqs_c[15]}]
set_property PACKAGE_PIN BA32 [get_ports {c0_ddr4_dqs_t[7]}]
set_property PACKAGE_PIN BA33 [get_ports {c0_ddr4_dqs_c[7]}]
set_property PACKAGE_PIN AU29 [get_ports {c0_ddr4_dqs_t[12]}]
set_property PACKAGE_PIN AU30 [get_ports {c0_ddr4_dqs_c[12]}]
set_property PACKAGE_PIN BB35 [get_ports {c0_ddr4_dqs_t[4]}]
set_property PACKAGE_PIN BB36 [get_ports {c0_ddr4_dqs_c[4]}]
set_property PACKAGE_PIN AY27 [get_ports {c0_ddr4_dqs_t[13]}]
set_property PACKAGE_PIN AY28 [get_ports {c0_ddr4_dqs_c[13]}]
set_property PACKAGE_PIN AV38 [get_ports {c0_ddr4_ck_t[0]}]
set_property PACKAGE_PIN AW38 [get_ports {c0_ddr4_ck_c[0]}]
set_property PACKAGE_PIN BC31 [get_ports {c0_ddr4_dqs_t[5]}]
set_property PACKAGE_PIN BD31 [get_ports {c0_ddr4_dqs_c[5]}]
set_property PACKAGE_PIN BD26 [get_ports {c0_ddr4_dqs_t[3]}]
set_property PACKAGE_PIN BE26 [get_ports {c0_ddr4_dqs_c[3]}]
set_property PACKAGE_PIN BD28 [get_ports {c0_ddr4_dqs_t[2]}]
set_property PACKAGE_PIN BD29 [get_ports {c0_ddr4_dqs_c[2]}]
set_property PACKAGE_PIN AL28 [get_ports {c0_ddr4_dqs_t[10]}]
set_property PACKAGE_PIN AL29 [get_ports {c0_ddr4_dqs_c[10]}]
set_property PACKAGE_PIN AR30 [get_ports {c0_ddr4_dqs_t[11]}]
set_property PACKAGE_PIN AT30 [get_ports {c0_ddr4_dqs_c[11]}]
set_property PACKAGE_PIN AW25 [get_ports c1_ddr4_act_n]
set_property PACKAGE_PIN AN24 [get_ports {c1_ddr4_adr[0]}]
set_property PACKAGE_PIN AT24 [get_ports {c1_ddr4_adr[1]}]
set_property PACKAGE_PIN AW24 [get_ports {c1_ddr4_adr[2]}]
set_property PACKAGE_PIN AN26 [get_ports {c1_ddr4_adr[3]}]
set_property PACKAGE_PIN AY22 [get_ports {c1_ddr4_adr[4]}]
set_property PACKAGE_PIN AY23 [get_ports {c1_ddr4_adr[5]}]
set_property PACKAGE_PIN AV24 [get_ports {c1_ddr4_adr[6]}]
set_property PACKAGE_PIN BA22 [get_ports {c1_ddr4_adr[7]}]
set_property PACKAGE_PIN AY25 [get_ports {c1_ddr4_adr[8]}]
set_property PACKAGE_PIN BA23 [get_ports {c1_ddr4_adr[9]}]
set_property PACKAGE_PIN AM26 [get_ports {c1_ddr4_adr[10]}]
set_property PACKAGE_PIN BA25 [get_ports {c1_ddr4_adr[11]}]
set_property PACKAGE_PIN BB22 [get_ports {c1_ddr4_adr[12]}]
set_property PACKAGE_PIN AL24 [get_ports {c1_ddr4_adr[13]}]
set_property PACKAGE_PIN AL25 [get_ports {c1_ddr4_adr[14]}]
set_property PACKAGE_PIN AM25 [get_ports {c1_ddr4_adr[15]}]
set_property PACKAGE_PIN AN23 [get_ports {c1_ddr4_adr[16]}]
set_property PACKAGE_PIN AU24 [get_ports {c1_ddr4_ba[0]}]
set_property PACKAGE_PIN AP26 [get_ports {c1_ddr4_ba[1]}]
set_property PACKAGE_PIN BC22 [get_ports {c1_ddr4_bg[0]}]
set_property PACKAGE_PIN AW26 [get_ports {c1_ddr4_bg[1]}]
set_property PACKAGE_PIN BB25 [get_ports {c1_ddr4_cke[0]}]
set_property PACKAGE_PIN AV23 [get_ports {c1_ddr4_cs_n[0]}]
set_property PACKAGE_PIN BD9 [get_ports {c1_ddr4_dq[0]}]
set_property PACKAGE_PIN BD7 [get_ports {c1_ddr4_dq[1]}]
set_property PACKAGE_PIN BC7 [get_ports {c1_ddr4_dq[2]}]
set_property PACKAGE_PIN BD8 [get_ports {c1_ddr4_dq[3]}]
set_property PACKAGE_PIN BD10 [get_ports {c1_ddr4_dq[4]}]
set_property PACKAGE_PIN BE10 [get_ports {c1_ddr4_dq[5]}]
set_property PACKAGE_PIN BE7 [get_ports {c1_ddr4_dq[6]}]
set_property PACKAGE_PIN BF7 [get_ports {c1_ddr4_dq[7]}]
set_property PACKAGE_PIN AU13 [get_ports {c1_ddr4_dq[8]}]
set_property PACKAGE_PIN AV13 [get_ports {c1_ddr4_dq[9]}]
set_property PACKAGE_PIN AW13 [get_ports {c1_ddr4_dq[10]}]
set_property PACKAGE_PIN AW14 [get_ports {c1_ddr4_dq[11]}]
set_property PACKAGE_PIN AU14 [get_ports {c1_ddr4_dq[12]}]
set_property PACKAGE_PIN AY11 [get_ports {c1_ddr4_dq[13]}]
set_property PACKAGE_PIN AV14 [get_ports {c1_ddr4_dq[14]}]
set_property PACKAGE_PIN BA11 [get_ports {c1_ddr4_dq[15]}]
set_property PACKAGE_PIN BA12 [get_ports {c1_ddr4_dq[16]}]
set_property PACKAGE_PIN BB12 [get_ports {c1_ddr4_dq[17]}]
set_property PACKAGE_PIN BA13 [get_ports {c1_ddr4_dq[18]}]
set_property PACKAGE_PIN BA14 [get_ports {c1_ddr4_dq[19]}]
set_property PACKAGE_PIN BC9 [get_ports {c1_ddr4_dq[20]}]
set_property PACKAGE_PIN BB9 [get_ports {c1_ddr4_dq[21]}]
set_property PACKAGE_PIN BA7 [get_ports {c1_ddr4_dq[22]}]
set_property PACKAGE_PIN BA8 [get_ports {c1_ddr4_dq[23]}]
set_property PACKAGE_PIN AN13 [get_ports {c1_ddr4_dq[24]}]
set_property PACKAGE_PIN AR13 [get_ports {c1_ddr4_dq[25]}]
set_property PACKAGE_PIN AM13 [get_ports {c1_ddr4_dq[26]}]
set_property PACKAGE_PIN AP13 [get_ports {c1_ddr4_dq[27]}]
set_property PACKAGE_PIN AM14 [get_ports {c1_ddr4_dq[28]}]
set_property PACKAGE_PIN AR15 [get_ports {c1_ddr4_dq[29]}]
set_property PACKAGE_PIN AL14 [get_ports {c1_ddr4_dq[30]}]
set_property PACKAGE_PIN AT15 [get_ports {c1_ddr4_dq[31]}]
set_property PACKAGE_PIN BE13 [get_ports {c1_ddr4_dq[32]}]
set_property PACKAGE_PIN BD14 [get_ports {c1_ddr4_dq[33]}]
set_property PACKAGE_PIN BF12 [get_ports {c1_ddr4_dq[34]}]
set_property PACKAGE_PIN BD13 [get_ports {c1_ddr4_dq[35]}]
set_property PACKAGE_PIN BD15 [get_ports {c1_ddr4_dq[36]}]
set_property PACKAGE_PIN BD16 [get_ports {c1_ddr4_dq[37]}]
set_property PACKAGE_PIN BF14 [get_ports {c1_ddr4_dq[38]}]
set_property PACKAGE_PIN BF13 [get_ports {c1_ddr4_dq[39]}]
set_property PACKAGE_PIN AY17 [get_ports {c1_ddr4_dq[40]}]
set_property PACKAGE_PIN BA17 [get_ports {c1_ddr4_dq[41]}]
set_property PACKAGE_PIN AY18 [get_ports {c1_ddr4_dq[42]}]
set_property PACKAGE_PIN BA18 [get_ports {c1_ddr4_dq[43]}]
set_property PACKAGE_PIN BA15 [get_ports {c1_ddr4_dq[44]}]
set_property PACKAGE_PIN BB15 [get_ports {c1_ddr4_dq[45]}]
set_property PACKAGE_PIN BC11 [get_ports {c1_ddr4_dq[46]}]
set_property PACKAGE_PIN BD11 [get_ports {c1_ddr4_dq[47]}]
set_property PACKAGE_PIN AV16 [get_ports {c1_ddr4_dq[48]}]
set_property PACKAGE_PIN AV17 [get_ports {c1_ddr4_dq[49]}]
set_property PACKAGE_PIN AU16 [get_ports {c1_ddr4_dq[50]}]
set_property PACKAGE_PIN AU17 [get_ports {c1_ddr4_dq[51]}]
set_property PACKAGE_PIN BB17 [get_ports {c1_ddr4_dq[52]}]
set_property PACKAGE_PIN BB16 [get_ports {c1_ddr4_dq[53]}]
set_property PACKAGE_PIN AT18 [get_ports {c1_ddr4_dq[54]}]
set_property PACKAGE_PIN AT17 [get_ports {c1_ddr4_dq[55]}]
set_property PACKAGE_PIN AM15 [get_ports {c1_ddr4_dq[56]}]
set_property PACKAGE_PIN AL15 [get_ports {c1_ddr4_dq[57]}]
set_property PACKAGE_PIN AN17 [get_ports {c1_ddr4_dq[58]}]
set_property PACKAGE_PIN AN16 [get_ports {c1_ddr4_dq[59]}]
set_property PACKAGE_PIN AR18 [get_ports {c1_ddr4_dq[60]}]
set_property PACKAGE_PIN AP18 [get_ports {c1_ddr4_dq[61]}]
set_property PACKAGE_PIN AL17 [get_ports {c1_ddr4_dq[62]}]
set_property PACKAGE_PIN AL16 [get_ports {c1_ddr4_dq[63]}]
set_property PACKAGE_PIN BF25 [get_ports {c1_ddr4_dq[64]}]
set_property PACKAGE_PIN BF24 [get_ports {c1_ddr4_dq[65]}]
set_property PACKAGE_PIN BD25 [get_ports {c1_ddr4_dq[66]}]
set_property PACKAGE_PIN BE25 [get_ports {c1_ddr4_dq[67]}]
set_property PACKAGE_PIN BD23 [get_ports {c1_ddr4_dq[68]}]
set_property PACKAGE_PIN BC23 [get_ports {c1_ddr4_dq[69]}]
set_property PACKAGE_PIN BF23 [get_ports {c1_ddr4_dq[70]}]
set_property PACKAGE_PIN BE23 [get_ports {c1_ddr4_dq[71]}]
set_property PACKAGE_PIN AW23 [get_ports {c1_ddr4_odt[0]}]
set_property PACKAGE_PIN AR17 [get_ports c1_ddr4_reset_n]
set_property PACKAGE_PIN AT23 [get_ports c1_ddr4_parity]
set_property PACKAGE_PIN AW20 [get_ports c1_sys_clk_p]
set_property PACKAGE_PIN AW19 [get_ports c1_sys_clk_n]
set_property PACKAGE_PIN BF10 [get_ports {c1_ddr4_dqs_t[0]}]
set_property PACKAGE_PIN BF9 [get_ports {c1_ddr4_dqs_c[0]}]
set_property PACKAGE_PIN BE12 [get_ports {c1_ddr4_dqs_t[8]}]
set_property PACKAGE_PIN BE11 [get_ports {c1_ddr4_dqs_c[8]}]
set_property PACKAGE_PIN BC24 [get_ports {c1_ddr4_dqs_t[16]}]
set_property PACKAGE_PIN BD24 [get_ports {c1_ddr4_dqs_c[16]}]
set_property PACKAGE_PIN BE15 [get_ports {c1_ddr4_dqs_t[9]}]
set_property PACKAGE_PIN BF15 [get_ports {c1_ddr4_dqs_c[9]}]
set_property PACKAGE_PIN BE8 [get_ports {c1_ddr4_dqs_t[1]}]
set_property PACKAGE_PIN BF8 [get_ports {c1_ddr4_dqs_c[1]}]
set_property PACKAGE_PIN BE22 [get_ports {c1_ddr4_dqs_t[17]}]
set_property PACKAGE_PIN BF22 [get_ports {c1_ddr4_dqs_c[17]}]
set_property PACKAGE_PIN AP16 [get_ports {c1_ddr4_dqs_t[14]}]
set_property PACKAGE_PIN AR16 [get_ports {c1_ddr4_dqs_c[14]}]
set_property PACKAGE_PIN AT14 [get_ports {c1_ddr4_dqs_t[6]}]
set_property PACKAGE_PIN AT13 [get_ports {c1_ddr4_dqs_c[6]}]
set_property PACKAGE_PIN AM17 [get_ports {c1_ddr4_dqs_t[15]}]
set_property PACKAGE_PIN AM16 [get_ports {c1_ddr4_dqs_c[15]}]
set_property PACKAGE_PIN AN14 [get_ports {c1_ddr4_dqs_t[7]}]
set_property PACKAGE_PIN AP14 [get_ports {c1_ddr4_dqs_c[7]}]
set_property PACKAGE_PIN AV18 [get_ports {c1_ddr4_dqs_t[12]}]
set_property PACKAGE_PIN AW18 [get_ports {c1_ddr4_dqs_c[12]}]
set_property PACKAGE_PIN BB11 [get_ports {c1_ddr4_dqs_t[4]}]
set_property PACKAGE_PIN BB10 [get_ports {c1_ddr4_dqs_c[4]}]
set_property PACKAGE_PIN AW16 [get_ports {c1_ddr4_dqs_t[13]}]
set_property PACKAGE_PIN AY16 [get_ports {c1_ddr4_dqs_c[13]}]
set_property PACKAGE_PIN AT25 [get_ports {c1_ddr4_ck_t[0]}]
set_property PACKAGE_PIN AU25 [get_ports {c1_ddr4_ck_c[0]}]
set_property PACKAGE_PIN BA10 [get_ports {c1_ddr4_dqs_t[5]}]
set_property PACKAGE_PIN BA9 [get_ports {c1_ddr4_dqs_c[5]}]
set_property PACKAGE_PIN AY13 [get_ports {c1_ddr4_dqs_t[3]}]
set_property PACKAGE_PIN AY12 [get_ports {c1_ddr4_dqs_c[3]}]
set_property PACKAGE_PIN AW15 [get_ports {c1_ddr4_dqs_t[2]}]
set_property PACKAGE_PIN AY15 [get_ports {c1_ddr4_dqs_c[2]}]
set_property PACKAGE_PIN BC13 [get_ports {c1_ddr4_dqs_t[10]}]
set_property PACKAGE_PIN BC12 [get_ports {c1_ddr4_dqs_c[10]}]
set_property PACKAGE_PIN BB14 [get_ports {c1_ddr4_dqs_t[11]}]
set_property PACKAGE_PIN BC14 [get_ports {c1_ddr4_dqs_c[11]}]
set_property PACKAGE_PIN N4 [get_ports {gt_rxp_in[0]}]
set_property PACKAGE_PIN N3 [get_ports {gt_rxn_in[0]}]
set_property PACKAGE_PIN N9 [get_ports {gt_txp_out[0]}]
set_property PACKAGE_PIN N8 [get_ports {gt_txn_out[0]}]
set_property PACKAGE_PIN M10 [get_ports gt_refclk_n]
set_property PACKAGE_PIN M11 [get_ports gt_refclk_p]
set_property PACKAGE_PIN J16 [get_ports c300_p]
set_property PACKAGE_PIN H16 [get_ports c300_n]
set_property IOSTANDARD LVDS [get_ports c300_p]
set_property IOSTANDARD LVDS [get_ports c300_n]
create_clock -period 6.400 -name clk156 -waveform {0.000 3.200} [get_pins network_module_inst/ethernet_inst/inst/i_core_gtwiz_userclk_tx_inst_0/tx_clk_out_0]






########################################




connect_debug_port u_ila_0/probe0 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[0]_1[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_1[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_1[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_1[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_1[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_1[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_1[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_1[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_1[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_1[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_1[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_1[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_1[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_1[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_1[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_1[15]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[10]_11[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_11[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_11[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_11[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_11[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_11[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_11[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_11[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_11[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_11[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_11[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_11[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_11[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_11[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_11[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_11[15]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[11]_12[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_12[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_12[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_12[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_12[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_12[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_12[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_12[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_12[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_12[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_12[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_12[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_12[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_12[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_12[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_12[15]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[12]_13[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_13[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_13[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_13[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_13[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_13[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_13[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_13[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_13[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_13[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_13[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_13[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_13[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_13[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_13[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_13[15]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[13]_14[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_14[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_14[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_14[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_14[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_14[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_14[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_14[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_14[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_14[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_14[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_14[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_14[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_14[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_14[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_14[15]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[14]_15[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_15[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_15[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_15[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_15[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_15[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_15[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_15[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_15[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_15[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_15[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_15[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_15[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_15[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_15[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_15[15]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[15]_16[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_16[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_16[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_16[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_16[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_16[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_16[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_16[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_16[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_16[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_16[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_16[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_16[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_16[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_16[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_16[15]}]]
connect_debug_port u_ila_0/probe7 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[1]_2[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_2[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_2[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_2[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_2[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_2[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_2[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_2[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_2[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_2[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_2[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_2[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_2[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_2[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_2[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_2[15]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[2]_3[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_3[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_3[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_3[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_3[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_3[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_3[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_3[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_3[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_3[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_3[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_3[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_3[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_3[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_3[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_3[15]}]]
connect_debug_port u_ila_0/probe9 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[3]_4[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_4[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_4[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_4[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_4[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_4[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_4[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_4[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_4[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_4[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_4[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_4[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_4[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_4[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_4[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_4[15]}]]
connect_debug_port u_ila_0/probe10 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[4]_5[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_5[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_5[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_5[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_5[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_5[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_5[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_5[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_5[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_5[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_5[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_5[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_5[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_5[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_5[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_5[15]}]]
connect_debug_port u_ila_0/probe11 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[5]_6[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_6[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_6[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_6[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_6[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_6[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_6[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_6[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_6[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_6[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_6[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_6[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_6[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_6[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_6[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_6[15]}]]
connect_debug_port u_ila_0/probe12 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[6]_7[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_7[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_7[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_7[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_7[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_7[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_7[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_7[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_7[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_7[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_7[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_7[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_7[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_7[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_7[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_7[15]}]]
connect_debug_port u_ila_0/probe13 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[7]_8[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_8[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_8[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_8[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_8[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_8[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_8[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_8[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_8[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_8[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_8[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_8[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_8[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_8[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_8[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_8[15]}]]
connect_debug_port u_ila_0/probe14 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[8]_9[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_9[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_9[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_9[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_9[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_9[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_9[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_9[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_9[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_9[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_9[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_9[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_9[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_9[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_9[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_9[15]}]]
connect_debug_port u_ila_0/probe15 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[9]_10[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_10[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_10[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_10[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_10[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_10[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_10[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_10[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_10[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_10[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_10[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_10[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_10[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_10[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_10[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_10[15]}]]

connect_debug_port u_ila_0/probe0 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[0]_2[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_2[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_2[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_2[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_2[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_2[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_2[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_2[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_2[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_2[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_2[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_2[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_2[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_2[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_2[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[0]_2[15]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[10]_12[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_12[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_12[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_12[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_12[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_12[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_12[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_12[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_12[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_12[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_12[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_12[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_12[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_12[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_12[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[10]_12[15]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[11]_13[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_13[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_13[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_13[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_13[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_13[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_13[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_13[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_13[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_13[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_13[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_13[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_13[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_13[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_13[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[11]_13[15]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[12]_14[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_14[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_14[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_14[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_14[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_14[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_14[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_14[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_14[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_14[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_14[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_14[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_14[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_14[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_14[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[12]_14[15]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[13]_15[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_15[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_15[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_15[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_15[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_15[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_15[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_15[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_15[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_15[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_15[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_15[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_15[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_15[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_15[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[13]_15[15]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[14]_16[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_16[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_16[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_16[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_16[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_16[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_16[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_16[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_16[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_16[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_16[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_16[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_16[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_16[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_16[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[14]_16[15]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[15]_17[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_17[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_17[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_17[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_17[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_17[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_17[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_17[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_17[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_17[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_17[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_17[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_17[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_17[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_17[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[15]_17[15]}]]
connect_debug_port u_ila_0/probe7 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[1]_3[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_3[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_3[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_3[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_3[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_3[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_3[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_3[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_3[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_3[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_3[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_3[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_3[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_3[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_3[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[1]_3[15]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[2]_4[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_4[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_4[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_4[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_4[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_4[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_4[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_4[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_4[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_4[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_4[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_4[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_4[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_4[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_4[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[2]_4[15]}]]
connect_debug_port u_ila_0/probe9 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[3]_5[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_5[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_5[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_5[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_5[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_5[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_5[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_5[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_5[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_5[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_5[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_5[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_5[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_5[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_5[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[3]_5[15]}]]
connect_debug_port u_ila_0/probe10 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[4]_6[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_6[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_6[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_6[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_6[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_6[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_6[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_6[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_6[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_6[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_6[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_6[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_6[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_6[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_6[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[4]_6[15]}]]
connect_debug_port u_ila_0/probe11 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[5]_7[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_7[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_7[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_7[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_7[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_7[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_7[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_7[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_7[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_7[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_7[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_7[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_7[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_7[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_7[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[5]_7[15]}]]
connect_debug_port u_ila_0/probe12 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[6]_8[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_8[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_8[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_8[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_8[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_8[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_8[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_8[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_8[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_8[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_8[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_8[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_8[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_8[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_8[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[6]_8[15]}]]
connect_debug_port u_ila_0/probe13 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[7]_9[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_9[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_9[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_9[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_9[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_9[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_9[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_9[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_9[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_9[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_9[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_9[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_9[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_9[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_9[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[7]_9[15]}]]
connect_debug_port u_ila_0/probe14 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[8]_10[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_10[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_10[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_10[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_10[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_10[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_10[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_10[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_10[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_10[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_10[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_10[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_10[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_10[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_10[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[8]_10[15]}]]
connect_debug_port u_ila_0/probe15 [get_nets [list {multiuser_kvs_top/muuSessionMngr/locationPending[9]_11[0]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_11[1]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_11[2]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_11[3]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_11[4]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_11[5]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_11[6]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_11[7]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_11[8]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_11[9]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_11[10]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_11[11]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_11[12]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_11[13]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_11[14]} {multiuser_kvs_top/muuSessionMngr/locationPending[9]_11[15]}]]
connect_debug_port u_ila_0/probe16 [get_nets [list {multiuser_kvs_top/muuSessionMngr/packetInnerLast[0]} {multiuser_kvs_top/muuSessionMngr/packetInnerLast[1]} {multiuser_kvs_top/muuSessionMngr/packetInnerLast[2]} {multiuser_kvs_top/muuSessionMngr/packetInnerLast[3]} {multiuser_kvs_top/muuSessionMngr/packetInnerLast[4]} {multiuser_kvs_top/muuSessionMngr/packetInnerLast[5]} {multiuser_kvs_top/muuSessionMngr/packetInnerLast[6]} {multiuser_kvs_top/muuSessionMngr/packetInnerLast[7]} {multiuser_kvs_top/muuSessionMngr/packetInnerLast[8]} {multiuser_kvs_top/muuSessionMngr/packetInnerLast[9]} {multiuser_kvs_top/muuSessionMngr/packetInnerLast[10]} {multiuser_kvs_top/muuSessionMngr/packetInnerLast[11]} {multiuser_kvs_top/muuSessionMngr/packetInnerLast[12]} {multiuser_kvs_top/muuSessionMngr/packetInnerLast[13]} {multiuser_kvs_top/muuSessionMngr/packetInnerLast[14]} {multiuser_kvs_top/muuSessionMngr/packetInnerLast[15]}]]
connect_debug_port u_ila_0/probe30 [get_nets [list multiuser_kvs_top/muukvs_instance/free_ready]]
connect_debug_port u_ila_0/probe31 [get_nets [list multiuser_kvs_top/muukvs_instance/free_valid]]
connect_debug_port u_ila_0/probe32 [get_nets [list multiuser_kvs_top/muukvs_instance/fromset_ready]]
connect_debug_port u_ila_0/probe33 [get_nets [list multiuser_kvs_top/muukvs_instance/fromset_valid]]
connect_debug_port u_ila_0/probe42 [get_nets [list multiuser_kvs_top/muukvs_instance/key_ready]]
connect_debug_port u_ila_0/probe43 [get_nets [list multiuser_kvs_top/muukvs_instance/key_valid]]
connect_debug_port u_ila_0/probe44 [get_nets [list multiuser_kvs_top/muukvs_instance/malloc_ready]]
connect_debug_port u_ila_0/probe45 [get_nets [list multiuser_kvs_top/muukvs_instance/malloc_valid]]
connect_debug_port u_ila_0/probe46 [get_nets [list multiuser_kvs_top/muukvs_instance/meta_ready]]
connect_debug_port u_ila_0/probe47 [get_nets [list multiuser_kvs_top/muukvs_instance/meta_valid]]
connect_debug_port u_ila_0/probe48 [get_nets [list multiuser_kvs_top/muukvs_instance/mreq_ready]]
connect_debug_port u_ila_0/probe49 [get_nets [list multiuser_kvs_top/muukvs_instance/mreq_valid]]
connect_debug_port u_ila_0/probe53 [get_nets [list multiuser_kvs_top/muukvs_instance/tohash_ready]]
connect_debug_port u_ila_0/probe54 [get_nets [list multiuser_kvs_top/muukvs_instance/tohash_valid]]
connect_debug_port u_ila_0/probe55 [get_nets [list multiuser_kvs_top/muukvs_instance/towrite_b_ready]]
connect_debug_port u_ila_0/probe56 [get_nets [list multiuser_kvs_top/muukvs_instance/towrite_b_valid]]
connect_debug_port u_ila_0/probe68 [get_nets [list multiuser_kvs_top/muukvs_instance/value_last]]
connect_debug_port u_ila_0/probe69 [get_nets [list multiuser_kvs_top/muukvs_instance/value_ready]]
connect_debug_port u_ila_0/probe70 [get_nets [list multiuser_kvs_top/muukvs_instance/value_valid]]
connect_debug_port u_ila_0/probe71 [get_nets [list multiuser_kvs_top/muukvs_instance/writefb_ready]]
connect_debug_port u_ila_0/probe72 [get_nets [list multiuser_kvs_top/muukvs_instance/writefb_valid]]
connect_debug_port u_ila_0/probe73 [get_nets [list multiuser_kvs_top/muukvs_instance/writeout_b_ready]]
connect_debug_port u_ila_0/probe74 [get_nets [list multiuser_kvs_top/muukvs_instance/writeout_b_valid]]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 4 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list network_module_inst/ethernet_inst/inst/i_core_gtwiz_userclk_tx_inst_0/tx_clk_out_0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {loopback_inst/axis_listen_port_data[0]} {loopback_inst/axis_listen_port_data[1]} {loopback_inst/axis_listen_port_data[2]} {loopback_inst/axis_listen_port_data[3]} {loopback_inst/axis_listen_port_data[4]} {loopback_inst/axis_listen_port_data[5]} {loopback_inst/axis_listen_port_data[6]} {loopback_inst/axis_listen_port_data[7]} {loopback_inst/axis_listen_port_data[8]} {loopback_inst/axis_listen_port_data[9]} {loopback_inst/axis_listen_port_data[10]} {loopback_inst/axis_listen_port_data[11]} {loopback_inst/axis_listen_port_data[12]} {loopback_inst/axis_listen_port_data[13]} {loopback_inst/axis_listen_port_data[14]} {loopback_inst/axis_listen_port_data[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {loopback_inst/maxis_meta_data[0]} {loopback_inst/maxis_meta_data[1]} {loopback_inst/maxis_meta_data[2]} {loopback_inst/maxis_meta_data[3]} {loopback_inst/maxis_meta_data[4]} {loopback_inst/maxis_meta_data[5]} {loopback_inst/maxis_meta_data[6]} {loopback_inst/maxis_meta_data[7]} {loopback_inst/maxis_meta_data[8]} {loopback_inst/maxis_meta_data[9]} {loopback_inst/maxis_meta_data[10]} {loopback_inst/maxis_meta_data[11]} {loopback_inst/maxis_meta_data[12]} {loopback_inst/maxis_meta_data[13]} {loopback_inst/maxis_meta_data[14]} {loopback_inst/maxis_meta_data[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 64 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {loopback_inst/maxis_tx_data[0]} {loopback_inst/maxis_tx_data[1]} {loopback_inst/maxis_tx_data[2]} {loopback_inst/maxis_tx_data[3]} {loopback_inst/maxis_tx_data[4]} {loopback_inst/maxis_tx_data[5]} {loopback_inst/maxis_tx_data[6]} {loopback_inst/maxis_tx_data[7]} {loopback_inst/maxis_tx_data[8]} {loopback_inst/maxis_tx_data[9]} {loopback_inst/maxis_tx_data[10]} {loopback_inst/maxis_tx_data[11]} {loopback_inst/maxis_tx_data[12]} {loopback_inst/maxis_tx_data[13]} {loopback_inst/maxis_tx_data[14]} {loopback_inst/maxis_tx_data[15]} {loopback_inst/maxis_tx_data[16]} {loopback_inst/maxis_tx_data[17]} {loopback_inst/maxis_tx_data[18]} {loopback_inst/maxis_tx_data[19]} {loopback_inst/maxis_tx_data[20]} {loopback_inst/maxis_tx_data[21]} {loopback_inst/maxis_tx_data[22]} {loopback_inst/maxis_tx_data[23]} {loopback_inst/maxis_tx_data[24]} {loopback_inst/maxis_tx_data[25]} {loopback_inst/maxis_tx_data[26]} {loopback_inst/maxis_tx_data[27]} {loopback_inst/maxis_tx_data[28]} {loopback_inst/maxis_tx_data[29]} {loopback_inst/maxis_tx_data[30]} {loopback_inst/maxis_tx_data[31]} {loopback_inst/maxis_tx_data[32]} {loopback_inst/maxis_tx_data[33]} {loopback_inst/maxis_tx_data[34]} {loopback_inst/maxis_tx_data[35]} {loopback_inst/maxis_tx_data[36]} {loopback_inst/maxis_tx_data[37]} {loopback_inst/maxis_tx_data[38]} {loopback_inst/maxis_tx_data[39]} {loopback_inst/maxis_tx_data[40]} {loopback_inst/maxis_tx_data[41]} {loopback_inst/maxis_tx_data[42]} {loopback_inst/maxis_tx_data[43]} {loopback_inst/maxis_tx_data[44]} {loopback_inst/maxis_tx_data[45]} {loopback_inst/maxis_tx_data[46]} {loopback_inst/maxis_tx_data[47]} {loopback_inst/maxis_tx_data[48]} {loopback_inst/maxis_tx_data[49]} {loopback_inst/maxis_tx_data[50]} {loopback_inst/maxis_tx_data[51]} {loopback_inst/maxis_tx_data[52]} {loopback_inst/maxis_tx_data[53]} {loopback_inst/maxis_tx_data[54]} {loopback_inst/maxis_tx_data[55]} {loopback_inst/maxis_tx_data[56]} {loopback_inst/maxis_tx_data[57]} {loopback_inst/maxis_tx_data[58]} {loopback_inst/maxis_tx_data[59]} {loopback_inst/maxis_tx_data[60]} {loopback_inst/maxis_tx_data[61]} {loopback_inst/maxis_tx_data[62]} {loopback_inst/maxis_tx_data[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 129 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {loopback_inst/splitPreData[0]} {loopback_inst/splitPreData[1]} {loopback_inst/splitPreData[2]} {loopback_inst/splitPreData[3]} {loopback_inst/splitPreData[4]} {loopback_inst/splitPreData[5]} {loopback_inst/splitPreData[6]} {loopback_inst/splitPreData[7]} {loopback_inst/splitPreData[8]} {loopback_inst/splitPreData[9]} {loopback_inst/splitPreData[10]} {loopback_inst/splitPreData[11]} {loopback_inst/splitPreData[12]} {loopback_inst/splitPreData[13]} {loopback_inst/splitPreData[14]} {loopback_inst/splitPreData[15]} {loopback_inst/splitPreData[16]} {loopback_inst/splitPreData[17]} {loopback_inst/splitPreData[18]} {loopback_inst/splitPreData[19]} {loopback_inst/splitPreData[20]} {loopback_inst/splitPreData[21]} {loopback_inst/splitPreData[22]} {loopback_inst/splitPreData[23]} {loopback_inst/splitPreData[24]} {loopback_inst/splitPreData[25]} {loopback_inst/splitPreData[26]} {loopback_inst/splitPreData[27]} {loopback_inst/splitPreData[28]} {loopback_inst/splitPreData[29]} {loopback_inst/splitPreData[30]} {loopback_inst/splitPreData[31]} {loopback_inst/splitPreData[32]} {loopback_inst/splitPreData[33]} {loopback_inst/splitPreData[34]} {loopback_inst/splitPreData[35]} {loopback_inst/splitPreData[36]} {loopback_inst/splitPreData[37]} {loopback_inst/splitPreData[38]} {loopback_inst/splitPreData[39]} {loopback_inst/splitPreData[40]} {loopback_inst/splitPreData[41]} {loopback_inst/splitPreData[42]} {loopback_inst/splitPreData[43]} {loopback_inst/splitPreData[44]} {loopback_inst/splitPreData[45]} {loopback_inst/splitPreData[46]} {loopback_inst/splitPreData[47]} {loopback_inst/splitPreData[48]} {loopback_inst/splitPreData[49]} {loopback_inst/splitPreData[50]} {loopback_inst/splitPreData[51]} {loopback_inst/splitPreData[52]} {loopback_inst/splitPreData[53]} {loopback_inst/splitPreData[54]} {loopback_inst/splitPreData[55]} {loopback_inst/splitPreData[56]} {loopback_inst/splitPreData[57]} {loopback_inst/splitPreData[58]} {loopback_inst/splitPreData[59]} {loopback_inst/splitPreData[60]} {loopback_inst/splitPreData[61]} {loopback_inst/splitPreData[62]} {loopback_inst/splitPreData[63]} {loopback_inst/splitPreData[64]} {loopback_inst/splitPreData[65]} {loopback_inst/splitPreData[66]} {loopback_inst/splitPreData[67]} {loopback_inst/splitPreData[68]} {loopback_inst/splitPreData[69]} {loopback_inst/splitPreData[70]} {loopback_inst/splitPreData[71]} {loopback_inst/splitPreData[72]} {loopback_inst/splitPreData[73]} {loopback_inst/splitPreData[74]} {loopback_inst/splitPreData[75]} {loopback_inst/splitPreData[76]} {loopback_inst/splitPreData[77]} {loopback_inst/splitPreData[78]} {loopback_inst/splitPreData[79]} {loopback_inst/splitPreData[80]} {loopback_inst/splitPreData[81]} {loopback_inst/splitPreData[82]} {loopback_inst/splitPreData[83]} {loopback_inst/splitPreData[84]} {loopback_inst/splitPreData[85]} {loopback_inst/splitPreData[86]} {loopback_inst/splitPreData[87]} {loopback_inst/splitPreData[88]} {loopback_inst/splitPreData[89]} {loopback_inst/splitPreData[90]} {loopback_inst/splitPreData[91]} {loopback_inst/splitPreData[92]} {loopback_inst/splitPreData[93]} {loopback_inst/splitPreData[94]} {loopback_inst/splitPreData[95]} {loopback_inst/splitPreData[96]} {loopback_inst/splitPreData[97]} {loopback_inst/splitPreData[98]} {loopback_inst/splitPreData[99]} {loopback_inst/splitPreData[100]} {loopback_inst/splitPreData[101]} {loopback_inst/splitPreData[102]} {loopback_inst/splitPreData[103]} {loopback_inst/splitPreData[104]} {loopback_inst/splitPreData[105]} {loopback_inst/splitPreData[106]} {loopback_inst/splitPreData[107]} {loopback_inst/splitPreData[108]} {loopback_inst/splitPreData[109]} {loopback_inst/splitPreData[110]} {loopback_inst/splitPreData[111]} {loopback_inst/splitPreData[112]} {loopback_inst/splitPreData[113]} {loopback_inst/splitPreData[114]} {loopback_inst/splitPreData[115]} {loopback_inst/splitPreData[116]} {loopback_inst/splitPreData[117]} {loopback_inst/splitPreData[118]} {loopback_inst/splitPreData[119]} {loopback_inst/splitPreData[120]} {loopback_inst/splitPreData[121]} {loopback_inst/splitPreData[122]} {loopback_inst/splitPreData[123]} {loopback_inst/splitPreData[124]} {loopback_inst/splitPreData[125]} {loopback_inst/splitPreData[126]} {loopback_inst/splitPreData[127]} {loopback_inst/splitPreData[128]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 16 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {axis_rx_metadata_TDATA[0]} {axis_rx_metadata_TDATA[1]} {axis_rx_metadata_TDATA[2]} {axis_rx_metadata_TDATA[3]} {axis_rx_metadata_TDATA[4]} {axis_rx_metadata_TDATA[5]} {axis_rx_metadata_TDATA[6]} {axis_rx_metadata_TDATA[7]} {axis_rx_metadata_TDATA[8]} {axis_rx_metadata_TDATA[9]} {axis_rx_metadata_TDATA[10]} {axis_rx_metadata_TDATA[11]} {axis_rx_metadata_TDATA[12]} {axis_rx_metadata_TDATA[13]} {axis_rx_metadata_TDATA[14]} {axis_rx_metadata_TDATA[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 64 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {axis_tx_data_TDATA[0]} {axis_tx_data_TDATA[1]} {axis_tx_data_TDATA[2]} {axis_tx_data_TDATA[3]} {axis_tx_data_TDATA[4]} {axis_tx_data_TDATA[5]} {axis_tx_data_TDATA[6]} {axis_tx_data_TDATA[7]} {axis_tx_data_TDATA[8]} {axis_tx_data_TDATA[9]} {axis_tx_data_TDATA[10]} {axis_tx_data_TDATA[11]} {axis_tx_data_TDATA[12]} {axis_tx_data_TDATA[13]} {axis_tx_data_TDATA[14]} {axis_tx_data_TDATA[15]} {axis_tx_data_TDATA[16]} {axis_tx_data_TDATA[17]} {axis_tx_data_TDATA[18]} {axis_tx_data_TDATA[19]} {axis_tx_data_TDATA[20]} {axis_tx_data_TDATA[21]} {axis_tx_data_TDATA[22]} {axis_tx_data_TDATA[23]} {axis_tx_data_TDATA[24]} {axis_tx_data_TDATA[25]} {axis_tx_data_TDATA[26]} {axis_tx_data_TDATA[27]} {axis_tx_data_TDATA[28]} {axis_tx_data_TDATA[29]} {axis_tx_data_TDATA[30]} {axis_tx_data_TDATA[31]} {axis_tx_data_TDATA[32]} {axis_tx_data_TDATA[33]} {axis_tx_data_TDATA[34]} {axis_tx_data_TDATA[35]} {axis_tx_data_TDATA[36]} {axis_tx_data_TDATA[37]} {axis_tx_data_TDATA[38]} {axis_tx_data_TDATA[39]} {axis_tx_data_TDATA[40]} {axis_tx_data_TDATA[41]} {axis_tx_data_TDATA[42]} {axis_tx_data_TDATA[43]} {axis_tx_data_TDATA[44]} {axis_tx_data_TDATA[45]} {axis_tx_data_TDATA[46]} {axis_tx_data_TDATA[47]} {axis_tx_data_TDATA[48]} {axis_tx_data_TDATA[49]} {axis_tx_data_TDATA[50]} {axis_tx_data_TDATA[51]} {axis_tx_data_TDATA[52]} {axis_tx_data_TDATA[53]} {axis_tx_data_TDATA[54]} {axis_tx_data_TDATA[55]} {axis_tx_data_TDATA[56]} {axis_tx_data_TDATA[57]} {axis_tx_data_TDATA[58]} {axis_tx_data_TDATA[59]} {axis_tx_data_TDATA[60]} {axis_tx_data_TDATA[61]} {axis_tx_data_TDATA[62]} {axis_tx_data_TDATA[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {axis_tx_metadata_TDATA[0]} {axis_tx_metadata_TDATA[1]} {axis_tx_metadata_TDATA[2]} {axis_tx_metadata_TDATA[3]} {axis_tx_metadata_TDATA[4]} {axis_tx_metadata_TDATA[5]} {axis_tx_metadata_TDATA[6]} {axis_tx_metadata_TDATA[7]} {axis_tx_metadata_TDATA[8]} {axis_tx_metadata_TDATA[9]} {axis_tx_metadata_TDATA[10]} {axis_tx_metadata_TDATA[11]} {axis_tx_metadata_TDATA[12]} {axis_tx_metadata_TDATA[13]} {axis_tx_metadata_TDATA[14]} {axis_tx_metadata_TDATA[15]} {axis_tx_metadata_TDATA[16]} {axis_tx_metadata_TDATA[17]} {axis_tx_metadata_TDATA[18]} {axis_tx_metadata_TDATA[19]} {axis_tx_metadata_TDATA[20]} {axis_tx_metadata_TDATA[21]} {axis_tx_metadata_TDATA[22]} {axis_tx_metadata_TDATA[23]} {axis_tx_metadata_TDATA[24]} {axis_tx_metadata_TDATA[25]} {axis_tx_metadata_TDATA[26]} {axis_tx_metadata_TDATA[27]} {axis_tx_metadata_TDATA[28]} {axis_tx_metadata_TDATA[29]} {axis_tx_metadata_TDATA[30]} {axis_tx_metadata_TDATA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list loopback_inst/axis_listen_port_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list axis_rx_data_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list axis_rx_data_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list axis_rx_data_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list axis_rx_metadata_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list axis_tx_data_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list axis_tx_data_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list axis_tx_data_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list axis_tx_metadata_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list axis_tx_metadata_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list loopback_inst/maxis_meta_ready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list loopback_inst/maxis_meta_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list loopback_inst/maxis_tx_last]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list loopback_inst/maxis_tx_ready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list loopback_inst/maxis_tx_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list loopback_inst/port_opened]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list rx_axis_tlast_oc]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list rx_axis_tready_oc]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list rx_axis_tvalid_oc]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list loopback_inst/splitPreReady]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list loopback_inst/splitPreValid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list tx_axis_tlast_oc]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list tx_axis_tready_oc]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list tx_axis_tvalid_oc]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
